[project]
name = "shopping-intelligence-agent"
version = "1.0.0"
description = "Agentic AI Shopping Intelligence using LangGraph, MCP, Groq and Tavily"
requires-python = ">=3.11,<3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-multipart",
    "python-dotenv",
    "langchain",
    "langgraph",
    "langchain-groq",
    "langchain-mcp-adapters",
    "fastmcp",
    "tavily-python"
]